import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import { cookies } from "next/headers";
import { THEME_COLORS, type Theme } from "@/constants";
import "./globals.css";

const leagueSpartanSans = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const savedTheme = (await cookies()).get("color-theme");
  const theme = (savedTheme?.value ?? "theme-1") as Theme;
  const themeColors = THEME_COLORS[theme] ?? THEME_COLORS["theme-1"];

  return (
    <html
      lang='en'
      className={`${leagueSpartanSans.variable}`}
      data-color-theme={theme}
      style={themeColors}
    >
      <body>{children}</body>
    </html>
  );
}
